name: Issue OM1
on:
  pull_request:
    types: [closed]      # reaguje po zamknięciu PR
permissions:
  contents: write
  pull-requests: read
jobs:
  issue-om1:
    if: github.event.pull_request.merged == true && contains(join(fromJson('["om1","OM1"]'), ''), 'om1') != null
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build credential payload
        id: build
        env:
          PRNUM: ${{ github.event.pull_request.number }}
          MERGE_SHA: ${{ github.event.pull_request.merge_commit_sha }}
          SUBJECT: github:${{ github.event.pull_request.user.login }}
          ISSUER: origo:omega
        run: |
          TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          mkdir -p credentials/issued
          cat > payload.json <<EOF
          {"id":"vc:origo:om1:${PRNUM}",
           "issuer":"${ISSUER}",
           "subject":"${SUBJECT}",
           "level":"OM1",
           "evidence":["repo:${GITHUB_REPOSITORY}","pr:${PRNUM}","merge:${MERGE_SHA}"],
           "issuedAt":"${TS}"}
          EOF
          SIG=$(openssl dgst -sha256 -hmac "$OMEGA_SECRET" -binary payload.json | xxd -p -c 256)
          jq --arg sig "$SIG" '. + {signature_hmac_sha256: $sig}' payload.json > "credentials/issued/${{ github.event.pull_request.user.login }}-OM1.json"
          echo "made=1" >> $GITHUB_OUTPUT

      - name: Commit credential
        if: steps.build.outputs.made == '1'
        uses: EndBug/add-and-commit@v9
        with:
          message: "feat(cred): issue OM1 for @${{ github.event.pull_request.user.login }} (PR #${{ github.event.pull_request.number }})"
          add: "credentials/issued/*.json"

